services:
#    jana.example:
#        class: JanaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
      jana.ponto:
          class: JanaBundle\Services\PontoService
          arguments: ["@service_container","@doctrine.orm.entity_manager"]

      jana.tipo_ponto:
          class: JanaBundle\Services\TipoPontoService
          arguments: ["@service_container","@doctrine.orm.entity_manager"]

      jana.log_ponto:
          class: JanaBundle\Services\LogPontoService
          arguments: ["@service_container","@doctrine.orm.entity_manager"]

      jana.acao_log:
          class: JanaBundle\Services\AcaoLogService
          arguments: ["@service_container","@doctrine.orm.entity_manager"]